version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "python-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-tv8ux2x7bknb"
s3_prefix = "python-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
